# Generated by Django 5.1 on 2024-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='camada',
        ),
        migrations.RemoveField(
            model_name='pacientes',
            name='email',
        ),
        migrations.AddField(
            model_name='estudios',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudios',
            name='fecha_de_entrega',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='apellido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
