# Generated by Django 5.1 on 2024-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
