# Generated by Django 5.1 on 2024-09-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_pacientes_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='mail',
            new_name='email',
        ),
    ]
